const imagePool = {
  black: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop',
  white: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1200&auto=format&fit=crop',
  red: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=1200&auto=format&fit=crop',
  blue: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&auto=format&fit=crop',
  green: 'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=1200&auto=format&fit=crop',
}

const baseVariants = (prefix, price) => [
  { sku: `${prefix}-BK-8`, size: '8', color: 'Black', material: 'Mesh', width: 'Regular', price },
  { sku: `${prefix}-BK-9`, size: '9', color: 'Black', material: 'Mesh', width: 'Regular', price },
  { sku: `${prefix}-WH-10`, size: '10', color: 'White', material: 'Mesh', width: 'Regular', price },
  { sku: `${prefix}-RD-11`, size: '11', color: 'Red', material: 'Mesh', width: 'Regular', price },
]

export const dummyProducts = [
  {
    name: 'Nike Air Max 90',
    brand: 'Nike',
    description: 'Classic running silhouette with visible Air cushioning and durable waffle outsole.',
    shortDescription: 'Iconic runner with daily comfort.',
    gender: 'MEN',
    shoeType: 'Running',
    category: 'Athletic Shoes',
    basePrice: 129.99,
    featuredProduct: true,
    newArrival: false,
    images: [imagePool.black, imagePool.white, imagePool.red],
    variants: baseVariants('AM90', 129.99),
    specification: {
      material: 'Engineered mesh',
      soleMaterial: 'Rubber',
      upperMaterial: 'Textile + synthetic',
      closureType: 'Lace-Up',
      breathable: true,
      waterproof: false,
    },
  },
  {
    name: 'Adidas Ultraboost X',
    brand: 'Adidas',
    description: 'Responsive cushioning built for long-distance runs and all-day city wear.',
    shortDescription: 'Responsive runner with plush comfort.',
    gender: 'UNISEX',
    shoeType: 'Running',
    category: 'Performance Shoes',
    basePrice: 179.99,
    featuredProduct: true,
    newArrival: true,
    images: [imagePool.blue, imagePool.white, imagePool.green],
    variants: baseVariants('UBX', 179.99),
    specification: {
      material: 'Primeknit',
      soleMaterial: 'Continental Rubber',
      upperMaterial: 'Knit textile',
      closureType: 'Lace-Up',
      breathable: true,
      waterproof: false,
    },
  },
  {
    name: 'Converse Chuck Taylor Lift',
    brand: 'Converse',
    description: 'Platform-inspired casual sneaker with a timeless profile and durable canvas upper.',
    shortDescription: 'Platform casual classic.',
    gender: 'UNISEX',
    shoeType: 'Casual',
    category: 'Lifestyle Sneakers',
    basePrice: 74,
    featuredProduct: false,
    newArrival: true,
    images: [imagePool.white, imagePool.black],
    variants: baseVariants('CTL', 74),
    specification: {
      material: 'Canvas',
      soleMaterial: 'Rubber',
      upperMaterial: 'Canvas',
      closureType: 'Lace-Up',
      breathable: true,
      waterproof: false,
    },
  },
  {
    name: 'New Balance 574 Heritage',
    brand: 'New Balance',
    description: 'Retro runner with ENCAP cushioning for supportive comfort and clean everyday style.',
    shortDescription: 'Retro silhouette with modern support.',
    gender: 'MEN',
    shoeType: 'Casual',
    category: 'Lifestyle Sneakers',
    basePrice: 94.99,
    featuredProduct: false,
    newArrival: false,
    images: [imagePool.blue, imagePool.black],
    variants: baseVariants('NB574', 94.99),
    specification: {
      material: 'Suede',
      soleMaterial: 'Rubber',
      upperMaterial: 'Suede + mesh',
      closureType: 'Lace-Up',
      breathable: true,
      waterproof: false,
    },
  },
  {
    name: 'Puma Velocity Nitro',
    brand: 'Puma',
    description: 'Lightweight training shoe tuned for tempo sessions and cushioned gym transitions.',
    shortDescription: 'Lightweight trainer for speed sessions.',
    gender: 'UNISEX',
    shoeType: 'Training',
    category: 'Performance Shoes',
    basePrice: 119,
    featuredProduct: false,
    newArrival: true,
    images: [imagePool.green, imagePool.black],
    variants: baseVariants('PVN', 119),
    specification: {
      material: 'Knit mesh',
      soleMaterial: 'NITRO foam + rubber',
      upperMaterial: 'Textile',
      closureType: 'Lace-Up',
      breathable: true,
      waterproof: false,
    },
  },
]
